In [1]:
import numpy as np

In [2]:
# 数组（一维）
numpy_array1=np.array([1,2,3,4])
numpy_array2=np.array([10,20,30,40])
print(numpy_array1+numpy_array2)

[11 22 33 44]


In [4]:
# 二维数组--矩阵
numpy_array3=np.array([
         [1,2,3,4],
         [5,5,6,6]
     ])
print(numpy_array3)

[[1 2 3 4]
 [5 5 6 6]]


In [5]:
# 三维数组
np_ay4=np.array([
    [[1,2,3,4],[7,7,7,7]],
    [[1,2,3,4],[8,8,8,8]],
])
print(np_ay4)

[[[1 2 3 4]
  [7 7 7 7]]

 [[1 2 3 4]
  [8 8 8 8]]]


In [6]:
# 输出维度
print(np_ay4.ndim)

3


In [7]:
# 输出形状
print(np_ay4.shape)

(2, 2, 4)


In [9]:
# 生成数组
arr=np.arange(100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [10]:
arr=np.arange(0,100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [11]:
arr=np.arange(0,100,2) # 偶数形式
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [12]:
print(arr.dtype) #类型

int64


In [13]:
print(arr.size) # 获取数组个数，转换为多维数组的前提，比如50个，就可以是5X10，2X25

50


In [15]:
arr_2D=arr.reshape(5,10)
print(arr_2D)

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [17]:
# 3维
arr_3D=arr.reshape(5,2,5)
print(arr_3D)

[[[ 0  2  4  6  8]
  [10 12 14 16 18]]

 [[20 22 24 26 28]
  [30 32 34 36 38]]

 [[40 42 44 46 48]
  [50 52 54 56 58]]

 [[60 62 64 66 68]
  [70 72 74 76 78]]

 [[80 82 84 86 88]
  [90 92 94 96 98]]]


In [19]:
# 设置默认值
0
zeros_arr=np.zeros(10) #10个元素0
print(zeros_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
# 1 的三维数组
ones_arr=np.ones((4,2,3))
print(ones_arr)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [23]:
# 任意固定值
nices=np.full((4,2,3),69)
print(nices)

[[[69 69 69]
  [69 69 69]]

 [[69 69 69]
  [69 69 69]]

 [[69 69 69]
  [69 69 69]]

 [[69 69 69]
  [69 69 69]]]


In [26]:
# 生成时指定数据类型
nices=np.full((4,2,3),69,dtype=np.float32) # 注意是np.xx
print(nices)

[[[69. 69. 69.]
  [69. 69. 69.]]

 [[69. 69. 69.]
  [69. 69. 69.]]

 [[69. 69. 69.]
  [69. 69. 69.]]

 [[69. 69. 69.]
  [69. 69. 69.]]]


In [28]:
zeros_arr=np.zeros(10,dtype=np.float32)
print(zeros_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
## 随机数
random_arr1=np.random.random((3,4,5)) #不包含1，且为正数
print(random_arr1)

[[[0.3755131  0.38442274 0.73581174 0.0668482  0.87140065]
  [0.77297621 0.91880295 0.03554997 0.95298413 0.50214329]
  [0.20699594 0.72809698 0.09060106 0.94092175 0.14204516]
  [0.64737446 0.76707119 0.13158055 0.88566501 0.19840793]]

 [[0.08535962 0.01716356 0.04773153 0.62649087 0.49089315]
  [0.54464341 0.51022937 0.76348097 0.21283996 0.55976756]
  [0.45231046 0.41275127 0.57136378 0.79504404 0.81106348]
  [0.5476355  0.71913157 0.93941413 0.77673943 0.81544529]]

 [[0.95723261 0.12004459 0.60305256 0.10609468 0.33162748]
  [0.41278619 0.88668652 0.91823876 0.06661071 0.09565887]
  [0.95970131 0.88040675 0.94564656 0.66738688 0.67905154]
  [0.70609636 0.64355608 0.35043112 0.49725874 0.94575118]]]


In [33]:
random_arr2=np.random.randn(3,4,5) # 负数
print(random_arr2)

[[[-0.06782468  0.42217653  0.92525798 -0.3237112   0.40370047]
  [-1.34622668  1.35949284 -0.07225879 -0.18123322  0.89729776]
  [-0.20632431 -0.44806791  0.35132942  1.31746257 -0.35460554]
  [-1.18599897  0.14167702 -0.98422259 -0.125004   -0.65641607]]

 [[-0.8442847  -0.62134467  1.53615162  1.34028697  0.67387417]
  [ 0.71893205 -1.10849733  1.72065533  1.4648695  -0.12023768]
  [-0.45385315  1.53267541  0.20644428  2.68334058  0.74356462]
  [-0.46074901  2.398453    0.03664814 -0.09640003  0.31881649]]

 [[-1.00653934  1.82122209 -0.41391112  1.5649523   0.98906405]
  [ 0.71281109  0.53139975  0.25138841  0.66934767 -0.36448039]
  [-0.82051861 -2.09434504 -0.41682828 -0.2452068   1.38351834]
  [ 1.24859249  0.26266575  0.89567796 -0.12267436  0.59584513]]]


In [34]:
random_arr3=np.random.randint(2,69,size=(4,2,3)) # 整数的随机数，起点，终点，形状
print(random_arr3)

[[[59 59 56]
  [28 63 58]]

 [[47  8 35]
  [56 55 16]]

 [[21 58  2]
  [28  8 36]]

 [[33 52 41]
  [14 15 59]]]


In [39]:
# 索引
arr_2D=arr.reshape(5,10)
print(arr_2D)

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [37]:
print(arr_2D[1:,3])

[26 46 66 86]


In [38]:
print(arr_2D[1:,3:])

[[26 28 30 32 34 36 38]
 [46 48 50 52 54 56 58]
 [66 68 70 72 74 76 78]
 [86 88 90 92 94 96 98]]


In [40]:
print(arr_2D[1:3,3:6]) # 前闭后开原则

[[26 28 30]
 [46 48 50]]


In [41]:
print(arr_2D>=69) # 对每个值判断

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [43]:
mask=(arr_2D>=69)&(arr_2D<=95)
print(np.where(mask,arr_2D,np.nan)) #判定条件，对象，不符合判定条件的位置要显示的东西，如0

[[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan 70. 72. 74. 76. 78.]
 [80. 82. 84. 86. 88. 90. 92. 94. nan nan]]


In [44]:
# 获取符合条件的索引
print(np.argwhere(mask))

[[3 5]
 [3 6]
 [3 7]
 [3 8]
 [3 9]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]
 [4 5]
 [4 6]
 [4 7]]


In [45]:
### 广播,即框架自动匹配生成对应的形状，进行操作
#这里要对维度要要求
eye=np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
print(eye+np.array([0.1,0.2,0.3,0.4,0.5]))

[[1.1 0.2 0.3 0.4 0.5]
 [0.1 1.2 0.3 0.4 0.5]
 [0.1 0.2 1.3 0.4 0.5]
 [0.1 0.2 0.3 1.4 0.5]
 [0.1 0.2 0.3 0.4 1.5]]


In [47]:
print(eye+np.array([[10],[20],[30],[40],[50]])) #第一行加10，第二行+20...

[[11. 10. 10. 10. 10.]
 [20. 21. 20. 20. 20.]
 [30. 30. 31. 30. 30.]
 [40. 40. 40. 41. 40.]
 [50. 50. 50. 50. 51.]]


In [48]:
#获取数组的总和
print(np.sum(eye))

5.0


In [49]:
#获取数组的最大数值
print(np.max(eye+np.array([[10],[20],[30],[40],[50]])))

51.0


In [50]:
# 轴向
# axis=0,是指的行方向，从上到下
# axis=1,是指的列方向。从左到右



In [52]:
print((eye+np.array([[10],[20],[30],[40],[50]])).max(axis=0))

[50. 50. 50. 50. 51.]


In [53]:
arrt=np.unique(print(np.max(eye+np.array([[10],[20],[30],[40],[50]])))) # 去重

51.0


In [54]:
# 合并
print(np.concatenate(arr1,arr2))

NameError: name 'arr1' is not defined