In [1]:
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True) #PyTorch 会开始追踪对 x 进行的所有运算。
                        #只有 requires_grad=True 的张量，在反向传播（.backward()）时才会被计算梯度
                       #函数名带下划线 _ 表示原地（in-place）操作
x.grad  #默认值是None，PyTorch 中用来存储梯度值的属性

In [3]:
y=2*torch.dot(x,x) #相当于构造了一个关于x的关系
y  #标量

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad==4*x

tensor([True, True, True, True])

In [9]:
x.grad.zero_() #默认下，pytorch会积累梯度，故更新为0
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [17]:
#对非标量调用backword需要传入刚gradient参数
x.grad.zero_() 
y=x*x
y.sum()
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [18]:
x.grad.zero_() 
y=x*x
u=y.detach() #把y当作一个常数，而不是x的函数
z=u*x
z.sum().backward() #导数应该是u
x.grad==u

tensor([True, True, True, True])

In [19]:
x.grad.zero_() 
y.sum().backward()
x.grad==2*x

tensor([True, True, True, True])