In [1]:
import torch
from torch import nn

# 为了方便起见，我们定义了一个计算卷积层的函数。
# 此函数初始化卷积层权重，并对输入和输出提高和缩减相应的维数
def comp_conv2d(conv2d,X):
    # 这里的（1，1）是表示批量大小和通道都是1
    X = X.reshape((1,1)+X.shape) # (1, 1) + (8, 8) = (1, 1, 8, 8)。
    print('X.reshape:',X)
    Y=conv2d(X)
    print('Y:',Y)
    # 省略前两个维度：批量大小和通道
    return Y.reshape(Y.shape[2:])
    
# 请注意，这里每边都填充了1行或1列，因此总共添加了2行或2列
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1) # 输入输出通道都是1，卷积核是3*3，是将输入的X的上下左右都填充1行/列的0 的，里面权重是随机的，在和卷积核相乘
X = torch.rand(size=(8, 8))
print('X.shape: ',X)
comp_conv2d(conv2d, X).shape

X.shape:  tensor([[0.5653, 0.5885, 0.3769, 0.2191, 0.8001, 0.5307, 0.1241, 0.2431],
        [0.3366, 0.3477, 0.1270, 0.0523, 0.9967, 0.0065, 0.8048, 0.5607],
        [0.7299, 0.2429, 0.3599, 0.3829, 0.6091, 0.1544, 0.9868, 0.3208],
        [0.5423, 0.0367, 0.3859, 0.3613, 0.2381, 0.5288, 0.8676, 0.9233],
        [0.1856, 0.7441, 0.9153, 0.2764, 0.7975, 0.3233, 0.2196, 0.7170],
        [0.1551, 0.8750, 0.0281, 0.3156, 0.2419, 0.9912, 0.2421, 0.3089],
        [0.5942, 0.1812, 0.3800, 0.8876, 0.8319, 0.0023, 0.1411, 0.8891],
        [0.2598, 0.4691, 0.2763, 0.5051, 0.6643, 0.2862, 0.9762, 0.2978]])
X.reshape: tensor([[[[0.5653, 0.5885, 0.3769, 0.2191, 0.8001, 0.5307, 0.1241, 0.2431],
          [0.3366, 0.3477, 0.1270, 0.0523, 0.9967, 0.0065, 0.8048, 0.5607],
          [0.7299, 0.2429, 0.3599, 0.3829, 0.6091, 0.1544, 0.9868, 0.3208],
          [0.5423, 0.0367, 0.3859, 0.3613, 0.2381, 0.5288, 0.8676, 0.9233],
          [0.1856, 0.7441, 0.9153, 0.2764, 0.7975, 0.3233, 0.2196, 0.7170],
      

torch.Size([8, 8])

In [2]:
#步幅设置为2
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1, stride=2)
comp_conv2d(conv2d, X).shape

X.reshape: tensor([[[[0.5653, 0.5885, 0.3769, 0.2191, 0.8001, 0.5307, 0.1241, 0.2431],
          [0.3366, 0.3477, 0.1270, 0.0523, 0.9967, 0.0065, 0.8048, 0.5607],
          [0.7299, 0.2429, 0.3599, 0.3829, 0.6091, 0.1544, 0.9868, 0.3208],
          [0.5423, 0.0367, 0.3859, 0.3613, 0.2381, 0.5288, 0.8676, 0.9233],
          [0.1856, 0.7441, 0.9153, 0.2764, 0.7975, 0.3233, 0.2196, 0.7170],
          [0.1551, 0.8750, 0.0281, 0.3156, 0.2419, 0.9912, 0.2421, 0.3089],
          [0.5942, 0.1812, 0.3800, 0.8876, 0.8319, 0.0023, 0.1411, 0.8891],
          [0.2598, 0.4691, 0.2763, 0.5051, 0.6643, 0.2862, 0.9762, 0.2978]]]])
Y: tensor([[[[0.2289, 0.4427, 0.2919, 0.3387],
          [0.1922, 0.3522, 0.5573, 0.3792],
          [0.4086, 0.5871, 0.2525, 0.8771],
          [0.0315, 0.5827, 0.3829, 0.6389]]]], grad_fn=<ConvolutionBackward0>)


torch.Size([4, 4])

In [3]:
conv2d = nn.Conv2d(1, 1, kernel_size=(3, 5), padding=(0, 1), stride=(3, 4))
comp_conv2d(conv2d, X).shape


X.reshape: tensor([[[[0.5653, 0.5885, 0.3769, 0.2191, 0.8001, 0.5307, 0.1241, 0.2431],
          [0.3366, 0.3477, 0.1270, 0.0523, 0.9967, 0.0065, 0.8048, 0.5607],
          [0.7299, 0.2429, 0.3599, 0.3829, 0.6091, 0.1544, 0.9868, 0.3208],
          [0.5423, 0.0367, 0.3859, 0.3613, 0.2381, 0.5288, 0.8676, 0.9233],
          [0.1856, 0.7441, 0.9153, 0.2764, 0.7975, 0.3233, 0.2196, 0.7170],
          [0.1551, 0.8750, 0.0281, 0.3156, 0.2419, 0.9912, 0.2421, 0.3089],
          [0.5942, 0.1812, 0.3800, 0.8876, 0.8319, 0.0023, 0.1411, 0.8891],
          [0.2598, 0.4691, 0.2763, 0.5051, 0.6643, 0.2862, 0.9762, 0.2978]]]])
Y: tensor([[[[ 0.2926,  0.0016],
          [ 0.0435, -0.0322]]]], grad_fn=<ConvolutionBackward0>)


torch.Size([2, 2])

In [4]:
###
###
### 多通道输入与输出
###
###


In [5]:
import torch
from d2l import torch as d2l
# 多通道输入
def corr2d_multi_in(X,K):
    # 先遍历“X”和“K”的第0个维度（通道维度），再把它们加在一起
    return sum(d2l.corr2d(x,k) for x,k in zip(X,K))

In [6]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])


In [7]:
corr2d_multi_in(X, K)


tensor([[ 56.,  72.],
        [104., 120.]])

In [8]:
# 多输出通道


In [9]:
def corr2d_multi_in_out(X, K):
    # 迭代“K”的第0个维度，每次都对输入“X”执行互相关运算。
    # 最后将所有结果都叠加在一起
    return torch.stack([corr2d_multi_in(X, k) for k in K], 0)
K = torch.stack((K, K + 1, K + 2), 0) # 在0的维度stack
K.shape
print(K)

tensor([[[[0., 1.],
          [2., 3.]],

         [[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]],

         [[2., 3.],
          [4., 5.]]],


        [[[2., 3.],
          [4., 5.]],

         [[3., 4.],
          [5., 6.]]]])


In [10]:
corr2d_multi_in_out(X, K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [11]:
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h * w))
    K = K.reshape((c_o, c_i))
    # 全连接层中的矩阵乘法
    Y = torch.matmul(K, X)
    return Y.reshape((c_o, h, w))

# 1*1的卷积 等价于 全连接

In [12]:
X = torch.normal(0, 1, (3, 3, 3))
K = torch.normal(0, 1, (2, 3, 1, 1))
Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)
assert float(torch.abs(Y1 - Y2).sum()) < 1e-6