In [1]:
import torch


In [2]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
X=x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.tensor([[[3,1,4,3],[2,4,8,7],[1,2,4,5]]]).shape

torch.Size([1, 3, 4])

In [17]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,4]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  4.]]))

In [18]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
X.sum()

tensor(66.)

In [20]:
Y.sum()

tensor(33.)

In [22]:
a=torch.arange(3).reshape((3,1)) #因为维度一样 1，3*2
b=torch.arange(2).reshape((1,2)) #3*2
a,b #广播机制

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [24]:
a=torch.arange(4).reshape((4,1)) 
b=torch.arange(2).reshape((1,2)) 
a,b #广播机制

(tensor([[0],
         [1],
         [2],
         [3]]),
 tensor([[0, 1]]))

In [25]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [26]:
X[1]

tensor([4., 5., 6., 7.])

In [27]:
X[1,2]=99
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 99.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
X[0:1,:]=222 #前闭后开
X

tensor([[222., 222., 222., 222.],
        [111., 111., 111., 111.],
        [  8.,   9.,  10.,  11.]])

In [32]:
before=id(Y)
Y=Y+X
id(Y)==before

False

In [34]:
before=id(Y)
Y+=X
id(Y)==before

True

In [35]:
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [38]:
a=torch.tensor([3.5])
a, a.item(), float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)