In [1]:
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x[3]

tensor(3.)

In [3]:
len(x)

4

In [4]:
x.shape

torch.Size([4])

In [5]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [6]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [7]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [8]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone() #重新分配新内存，将A的副本分配给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [9]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [10]:
a=2
X,a+X,a*X,(a*x).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([4]))

In [11]:
A.sum()

tensor(190.)

In [12]:
A.mean(),A.numel(),A.sum()/A.numel()

(tensor(9.5000), 20, tensor(9.5000))

In [13]:
A[:,:]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [14]:
A.mean(axis=0)#axis=0 表示沿着第 0 维（行方向）压缩，对每一列求平均。

tensor([ 8.,  9., 10., 11.])

In [15]:
A.shape[0] #第零维的大小

5

In [16]:
A.sum(axis=0)

tensor([40., 45., 50., 55.])

In [17]:
sum_A=A.sum(axis=1,keepdims=True) # keepdime保持轴数不变
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [18]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [19]:
A,A.cumsum(axis=0) #向下累加

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

In [20]:
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y) #点积

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [21]:
torch.sum(x*y)

tensor(6.)

In [22]:
A.shape,x.shape,torch.mv(A,x) #矩阵*向量

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [23]:
B=torch.ones(4,3) #矩阵*矩阵
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [24]:
u=torch.tensor([3.0,-4.0]) #范数即向量元素平方和的平方根
torch.norm(u)

tensor(5.)

In [25]:
torch.abs(u).sum() #L1范数，向量元素的绝对值之和

tensor(7.)

In [26]:
torch.norm(torch.ones((4,9))) #f范数，矩阵元素的平方和的平方根

tensor(6.)

In [27]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [29]:
A.shape

torch.Size([5, 4])

In [41]:
G=A.sum(axis=0,keepdims=True)
G.shape

torch.Size([1, 4])

In [37]:
G

(tensor([40., 45., 50., 55.]),
 (tensor([40., 45., 50., 55.]), tensor([40., 45., 50., 55.])))

In [43]:
r=torch.ones((2,5,4))
r.shape

torch.Size([2, 5, 4])

In [44]:
r

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [45]:
r.sum(axis=1)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [46]:
r.sum(axis=0)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [47]:
r.sum(axis=2)

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])