In [1]:
# 不带参数的层

In [2]:
import torch
import torch.nn.functional as F
from torch import nn

In [3]:
# 构造一个没有任何参数的自定义层
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,X):
        return X-X.mean()

In [5]:
layer=CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5])) #会调用pytorch的call函数，然后调用本层的forward函数

tensor([-2., -1.,  0.,  1.,  2.])

In [7]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y=net(torch.rand(4,8)) #传入的（4个批次，8个特征）
                        #nn.Linear(in_features, out_features) 的输入必须是(batch_size, in_features)
Y.mean()

tensor(7.4506e-09, grad_fn=<MeanBackward0>)

In [8]:
## 带参数的层

In [10]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
print(linear.weight)
linear.bias

Parameter containing:
tensor([[ 0.5159, -1.3905, -0.2648],
        [ 0.0311, -1.0744, -1.3298],
        [-1.0307, -0.2291, -0.2909],
        [ 0.8372, -0.1525,  0.3309],
        [ 0.7051,  0.2907,  0.2030]], requires_grad=True)


Parameter containing:
tensor([ 1.1345, -0.1223,  0.8481], requires_grad=True)

In [11]:
# 自定义层直接执行前向传播计算
linear(torch.rand(2, 5))


tensor([[2.1519, 0.0000, 0.0000],
        [2.3916, 0.0000, 0.5331]])

In [12]:
# 使用自定义层构建模型，就像使用内置的全连接层一样使用自定义层
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))


tensor([[0.],
        [0.]])